### ISSUE TITLE
MMM:Ship AI algorithm

### ISSUE THREAD

**Issue by joseffaghihi** [joseffaghihi/GamificationAlgebraConcepts#11]
Nicholas: 1 2 3 minions   take the time for user clicking on the first , the second and the third. Make the average of clicking.

Usef: 1 2 3 minions   take the time for user clicking on the first , the second and the third. Make the average of clicking.
if Usef_P < Nicholas_P 
slow, spawn minions with the same rate
   if (numbers of mistakes >=2)
        show the animation

```
if Usef_P numbers of mistakes ==0 
         start with dynamic problem
```

if Usef_P => Nicholas_P
 Fast spawning

```
    if (numbers of mistakes >=2)
         show the animation

    if Usef_P numbers of mistakes ==0 
        start with dynamic problem
```

**Comment by ghost** [comment]
This topic has been shifted towards the User Performance AI.
https://github.com/joseffaghihi/GamificationAlgebraConcepts/issues/13
