### ISSUE TITLE
[MMM:Ship]Bug: Dynamic Equation Generator Doesn't Move Indexes

### ISSUE THREAD

**Issue by ghost** [joseffaghihi/GamificationAlgebraConcepts#12]
As currently of the latest commit, the DEG does not shift the indexes left or right of the equals sign.  The DEG still treats the entire equation as if it is fully shifted to the left.

Example:
Ax^2 + Bx + C = NULL  --->>  Ax^2 + C = negated(Bx)

**Comment by ghost** [comment]
This should now be fixed in the latest commit.

**Comment by joseffaghihi** [comment]
I will look at this tomorrow or after tomorrow. Many thanks Tiger!!
