### ISSUE TITLE
[MMM:Ship] Mouse Cursor

### ISSUE THREAD

**Issue by donaggie6** [joseffaghihi/GamificationAlgebraConcepts#16]
Consider a large cursor during game play.  While trying to kick minions off the ladders, I frequently lost my standard cursor.  A larger cursor would be easier to find.  Think of the "sights" in games like the Halo, or Battlefield franchises.  They are always on and easy to find while moving from target to target.

**Comment by Davidizm** [comment]
Thank you. I will get on this right away.

Date: Mon, 24 Aug 2015 12:12:51 -0700

**Comment by ghost** [comment]
If you need my help to port it into game, let me know.  It'll be something new ;)

**Comment by Davidizm** [comment]
ok

Date: Mon, 24 Aug 2015 15:00:45 -0700

**Comment by ghost** [comment]
This feature is partially working and somewhat not.  The scripts should already be working, but the cursor does not yet appear.  This might be resolved soon....

**Comment by ghost** [comment]
Later today, I'll try to dig through the revisions and figure out what happened.

**Comment by ghost** [comment]
Fixed.
