### ISSUE TITLE
[MMM:Ship.AI] GameManager() Not Restarted

### ISSUE THREAD

**Issue by ghost** [joseffaghihi/GamificationAlgebraConcepts#25]
GameManager() instance is never restarted once the instance has been destroyed.  If the game is technically over by scores, the spawning actors will continue to be spawned regardless.

**Comment by Davidizm** [comment]
Sounds like this could be a job for a boolean :)

Date: Fri, 8 Jan 2016 17:50:57 -0800

**Comment by ghost** [comment]
Possibly, but there could be another way.

**Comment by ghost** [comment]
I might have resolved this issue in commit [ 14ffa2522b6298a92e8c0b3b8a7aa76742fabed4 ], but requires testing.

**Comment by ghost** [comment]
Looks like I have not hit the root of the problem yet; I'll keep looking....

**Comment by ghost** [comment]
Finally got it in commit [ 501f4b7d6733b73e1e536068131c83f0b448d580 ]
