### ISSUE TITLE
MovieTexture Support Deprecated

### ISSUE THREAD

**Issue by ghost** [joseffaghihi/GamificationAlgebraConcepts#29]
As QuickTime has been pulled due to critical security issues, the Unity team is going shift away from using QuickTime as a required dependency for MovieTextures to using a new API.

Please follow up with Unity Road Map progress for updates and how it will affect our project:  https://unity3d.com/unity/roadmap

**Comment by ghost** [comment]
Unity 5.6 is [released!](https://blogs.unity3d.com/2017/03/31/5-6-is-now-available-and-completes-the-unity-5-cycle/)  QuickTime is no longer a prerequisite.

**Comment by ghost** [comment]
As the legacy functionality still exists with no hinderance, we will keep the current functionality as is until an upgrade is absolutely necessary.

**Comment by derwaldgeist** [comment]
What is the replacement for Movie textures in more recent Unity versions? I see that Unity.2017 shows that it is deprecated, but there is no hint about a replacement in the docs.
