### ISSUE TITLE
Minion answers is not fixed when array is Rand() filled

### ISSUE THREAD

**Issue by ghost** [joseffaghihi/GamificationAlgebraConcepts#30]
It seems that when the first set of Rand() array is filled, the answer is fixed at the mid-tail with repetition.  However, when the array is filled again - the answer isn't fixed but completely random in its position.  Thus, meaning, the answer may not be in the mid-tail, but could lye in the head-tail.

**Comment by ghost** [comment]
I have marked this ticket as deprecated due to project shifts.

**Comment by joseffaghihi** [comment]
I think this problem is solved.
Thank you!
